import marimo

__generated_with = "0.20.2"
app = marimo.App(width="full")


@app.cell
def _():
    import json
    import higlass as hg

    return hg, json


@app.cell
def _(json):
    viewconfig = json.loads(
        r'''
{
  "editable": true,
  "trackSourceServers": [
    "/api/v1",
    "http://higlass.io/api/v1"
  ],
  "exportViewUrl": "/api/v1/viewconfs",
  "views": [
    {
      "initialXDomain": [
        1618096355.3485339,
        1620152102.7973564
      ],
      "initialYDomain": [
        1668217350.5394683,
        1668451333.0871353
      ],
      "tracks": {
        "top": [
          {
            "uid": "fcAYlRftSdy-qrriknpgZw",
            "type": "combined",
            "contents": [
              {
                "type": "horizontal-multivec",
                "uid": "ZBYXH6CHS22nE9_miKsq7w",
                "tilesetUid": "bDwyYCAzRWylyog7CIxUpA",
                "server": "https://resgen.io/api/v1",
                "options": {
                  "labelPosition": "topLeft",
                  "labelLeftMargin": 0,
                  "labelRightMargin": 0,
                  "labelTopMargin": 0,
                  "labelBottomMargin": 0,
                  "labelShowResolution": true,
                  "labelShowAssembly": true,
                  "labelColor": "black",
                  "labelTextOpacity": 0.4,
                  "minHeight": 100,
                  "valueScaling": "linear",
                  "trackBorderWidth": 0,
                  "trackBorderColor": "black",
                  "heatmapValueScaling": "linear",
                  "selectRowsAggregationMode": "mean",
                  "selectRowsAggregationWithRelativeHeight": true,
                  "selectRowsAggregationMethod": "client",
                  "selectRows": [
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    220,
                    221,
                    222,
                    223,
                    224,
                    225,
                    226,
                    227,
                    228,
                    229,
                    230,
                    231,
                    232,
                    233,
                    234,
                    235,
                    236,
                    237,
                    401,
                    402,
                    547,
                    548,
                    549,
                    550,
                    551,
                    552,
                    568,
                    569,
                    603,
                    606,
                    607,
                    626,
                    627,
                    628,
                    629,
                    630,
                    669,
                    670,
                    671,
                    672,
                    673,
                    674,
                    675,
                    676,
                    677,
                    678,
                    679,
                    680,
                    681,
                    682,
                    683,
                    684,
                    685,
                    686,
                    687,
                    688,
                    689,
                    690,
                    691,
                    692,
                    693,
                    694,
                    695,
                    696,
                    697,
                    698,
                    699,
                    700,
                    701,
                    702,
                    703,
                    704,
                    705,
                    706,
                    707,
                    708,
                    709,
                    710,
                    711,
                    712,
                    713,
                    714,
                    715,
                    716,
                    719,
                    720,
                    721,
                    722,
                    723,
                    724,
                    725,
                    726,
                    727,
                    728,
                    729,
                    730,
                    731,
                    732,
                    733,
                    734,
                    735,
                    736,
                    737,
                    738,
                    739,
                    740,
                    741,
                    742,
                    743,
                    744,
                    745,
                    746,
                    747,
                    748,
                    749,
                    750,
                    751,
                    752,
                    753,
                    754,
                    755,
                    756,
                    757,
                    758,
                    759,
                    760,
                    761,
                    762,
                    763,
                    764,
                    765,
                    766,
                    767,
                    768,
                    769,
                    770,
                    771,
                    772,
                    773,
                    774,
                    775,
                    776,
                    777,
                    778,
                    779,
                    780,
                    781,
                    782,
                    783,
                    784,
                    785,
                    786,
                    787,
                    788,
                    789,
                    790,
                    791,
                    792,
                    793,
                    794,
                    795,
                    392,
                    393,
                    581,
                    582,
                    623,
                    624,
                    625,
                    170,
                    171,
                    176,
                    177,
                    342,
                    343,
                    344,
                    345,
                    595,
                    596,
                    152,
                    153,
                    158,
                    159,
                    164,
                    165,
                    166,
                    167,
                    168,
                    169,
                    403,
                    404,
                    405,
                    406,
                    407,
                    408,
                    409,
                    410,
                    411,
                    412,
                    413,
                    414,
                    415,
                    416,
                    417,
                    418,
                    419,
                    420,
                    421,
                    422,
                    423,
                    424,
                    425,
                    426,
                    427,
                    428,
                    429,
                    430,
                    431,
                    432,
                    433,
                    434,
                    435,
                    436,
                    437,
                    438,
                    439,
                    440,
                    441,
                    442,
                    443,
                    444,
                    445,
                    446,
                    447,
                    448,
                    449,
                    450,
                    451,
                    452,
                    453,
                    454,
                    455,
                    456,
                    457,
                    458,
                    459,
                    460,
                    461,
                    462,
                    463,
                    464,
                    465,
                    466,
                    578,
                    579,
                    580,
                    591,
                    592,
                    597,
                    598,
                    136,
                    137,
                    156,
                    157,
                    180,
                    181,
                    184,
                    185,
                    593,
                    594,
                    599,
                    600,
                    394,
                    395,
                    396,
                    497,
                    498,
                    509,
                    510,
                    525,
                    526,
                    584,
                    585,
                    586,
                    587,
                    588,
                    589,
                    590,
                    615,
                    617,
                    618,
                    619,
                    620,
                    70,
                    71,
                    299,
                    300,
                    304,
                    305,
                    306,
                    307,
                    310,
                    311,
                    314,
                    315,
                    318,
                    319,
                    322,
                    323,
                    324,
                    325,
                    340,
                    341,
                    397,
                    398,
                    505,
                    506,
                    507,
                    508,
                    523,
                    524,
                    570,
                    571,
                    583,
                    616,
                    621,
                    622,
                    238,
                    239,
                    256,
                    257,
                    258,
                    259,
                    260,
                    261,
                    262,
                    263,
                    264,
                    265,
                    266,
                    267,
                    268,
                    269,
                    270,
                    271,
                    272,
                    273,
                    274,
                    275,
                    278,
                    279,
                    280,
                    281,
                    282,
                    283,
                    284,
                    285,
                    286,
                    287,
                    240,
                    241,
                    242,
                    243,
                    244,
                    245,
                    246,
                    247,
                    248,
                    249,
                    250,
                    251,
                    252,
                    253,
                    254,
                    255,
                    276,
                    277,
                    346,
                    347,
                    348,
                    349,
                    350,
                    351,
                    352,
                    353,
                    354,
                    355,
                    356,
                    357,
                    358,
                    359,
                    360,
                    361,
                    362,
                    363,
                    364,
                    365,
                    366,
                    367,
                    368,
                    369,
                    370,
                    371,
                    372,
                    373,
                    374,
                    375,
                    376,
                    377,
                    378,
                    379,
                    380,
                    381,
                    382,
                    383,
                    384,
                    385,
                    386,
                    387,
                    388,
                    389,
                    390,
                    391,
                    399,
                    400,
                    611,
                    612,
                    288,
                    291,
                    292,
                    293,
                    294,
                    312,
                    313,
                    68,
                    69,
                    289,
                    290,
                    295,
                    296,
                    316,
                    317,
                    320,
                    321,
                    297,
                    298,
                    301,
                    302,
                    303,
                    308,
                    309,
                    467,
                    468,
                    469,
                    470,
                    471,
                    472,
                    473,
                    474,
                    475,
                    476,
                    477,
                    478,
                    479,
                    480,
                    481,
                    482,
                    483,
                    484,
                    485,
                    486,
                    487,
                    488,
                    489,
                    490,
                    491,
                    492,
                    493,
                    494,
                    495,
                    496,
                    557,
                    558,
                    613,
                    614,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99,
                    100,
                    101,
                    102,
                    103,
                    104,
                    105,
                    106,
                    107,
                    108,
                    109,
                    110,
                    111,
                    112,
                    113,
                    114,
                    115,
                    116,
                    117,
                    118,
                    119,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125,
                    126,
                    127,
                    140,
                    141,
                    562,
                    563,
                    499,
                    500,
                    501,
                    502,
                    503,
                    504,
                    511,
                    512,
                    513,
                    514,
                    515,
                    516,
                    517,
                    518,
                    519,
                    520,
                    521,
                    522,
                    560,
                    561,
                    564,
                    565,
                    566,
                    567,
                    572,
                    573,
                    574,
                    575,
                    576,
                    577,
                    609,
                    610,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    559,
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    190,
                    191,
                    553,
                    554,
                    326,
                    327,
                    328,
                    329,
                    330,
                    331,
                    332,
                    333,
                    334,
                    335,
                    336,
                    337,
                    338,
                    339,
                    631,
                    632,
                    633,
                    634,
                    635,
                    636,
                    637,
                    638,
                    639,
                    640,
                    641,
                    642,
                    643,
                    644,
                    645,
                    646,
                    647,
                    648,
                    649,
                    650,
                    651,
                    652,
                    653,
                    654,
                    655,
                    656,
                    657,
                    658,
                    659,
                    660,
                    661,
                    662,
                    663,
                    664,
                    665,
                    666,
                    667,
                    668,
                    527,
                    528,
                    529,
                    530,
                    531,
                    532,
                    533,
                    534,
                    535,
                    536,
                    537,
                    538,
                    539,
                    540,
                    541,
                    542,
                    543,
                    544,
                    545,
                    546,
                    602,
                    608,
                    717,
                    718,
                    128,
                    129,
                    130,
                    131,
                    132,
                    133,
                    134,
                    135,
                    138,
                    139,
                    142,
                    143,
                    144,
                    145,
                    146,
                    147,
                    148,
                    149,
                    150,
                    151,
                    154,
                    155,
                    160,
                    161,
                    162,
                    163,
                    172,
                    173,
                    174,
                    175,
                    178,
                    179,
                    182,
                    183,
                    186,
                    187,
                    188,
                    189,
                    555,
                    556,
                    601,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    604,
                    605,
                    192,
                    193,
                    194,
                    195,
                    196,
                    197,
                    198,
                    199,
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    209,
                    210,
                    211,
                    212,
                    213,
                    214,
                    215,
                    216,
                    217,
                    218,
                    219,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67
                  ],
                  "colorbarBackgroundColor": "#ffffff",
                  "colorbarPosition": "topRight",
                  "zeroValueColor": null,
                  "name": "TCGA_ATAC_NMF_sort_100bp",
                  "scaleStartPercent": "0.00000",
                  "scaleEndPercent": "1.00000",
                  "colorRange": [
                    "rgba(255,255,255,1)",
                    "rgba(0,0,0,1)"
                  ]
                },
                "width": 3365,
                "height": 301
              }
            ],
            "height": 301,
            "options": {},
            "width": 3365
          },
          {
            "uid": "Pe2ddGUuRRCyvDCRhBO5tg",
            "type": "combined",
            "contents": [
              {
                "type": "bedlike",
                "uid": "HO-scxSuSaaT8AMtnb7ojw",
                "tilesetUid": "ZHrss5swRmOsmTqQpSCo0Q",
                "server": "https://resgen.io/api/v1",
                "options": {
                  "alternating": false,
                  "annotationStyle": "box",
                  "fillColor": "blue",
                  "fillOpacity": 1,
                  "fontSize": "10",
                  "axisPositionHorizontal": "right",
                  "labelColor": "black",
                  "labelPosition": "hidden",
                  "labelLeftMargin": 0,
                  "labelRightMargin": 0,
                  "labelTopMargin": 0,
                  "labelBottomMargin": 0,
                  "minHeight": 20,
                  "maxAnnotationHeight": null,
                  "trackBorderWidth": 0,
                  "trackBorderColor": "black",
                  "valueColumn": null,
                  "colorEncoding": "itemRgb",
                  "showTexts": false,
                  "colorRange": [
                    "#000000",
                    "#652537",
                    "#bf5458",
                    "#fba273",
                    "#ffffe0"
                  ],
                  "colorEncodingRange": false,
                  "separatePlusMinusStrands": true,
                  "annotationHeight": 16,
                  "name": "cCREs_v4_colored_CLH.bed.gz"
                },
                "width": 3365,
                "height": 36
              }
            ],
            "height": 36,
            "options": {},
            "width": 3365
          },
          {
            "uid": "QzuxvU7JSWaQVGAK4UU95A",
            "type": "combined",
            "contents": [
              {
                "type": "horizontal-gene-annotations",
                "uid": "EoP9CoLGTYSiS9zc2iw8YQ",
                "tilesetUid": "M9A9klpwTci5Vf4bHZ864g",
                "server": "https://resgen.io/api/v1",
                "options": {
                  "fontSize": 10,
                  "labelColor": "black",
                  "labelBackgroundColor": "#ffffff",
                  "labelPosition": "hidden",
                  "labelLeftMargin": 0,
                  "labelRightMargin": 0,
                  "labelTopMargin": 0,
                  "labelBottomMargin": 0,
                  "minHeight": 24,
                  "plusStrandColor": "blue",
                  "minusStrandColor": "red",
                  "trackBorderWidth": 0,
                  "trackBorderColor": "black",
                  "showMousePosition": false,
                  "mousePositionColor": "#000000",
                  "geneAnnotationHeight": 16,
                  "geneLabelPosition": "outside",
                  "geneStrandSpacing": 4,
                  "name": "Gene Annotations (hg38)"
                },
                "width": 3365,
                "height": 63
              }
            ],
            "height": 63,
            "options": {},
            "width": 3365
          },
          {
            "uid": "A-xcXXSNQ9Wzg2xJFUtoxA",
            "type": "combined",
            "contents": [
              {
                "type": "chromosome-labels",
                "uid": "WU_0sbviT-2eh9jJRnX_iQ",
                "tilesetUid": "ZpZ8c5JJRUS1J7ZkofcUrg",
                "server": "https://resgen.io/api/v1",
                "options": {
                  "color": "#808080",
                  "stroke": "#ffffff",
                  "fontSize": 12,
                  "fontIsLeftAligned": false,
                  "showMousePosition": false,
                  "mousePositionColor": "#000000",
                  "reverseOrientation": false,
                  "name": "Chromosome Info (hg38)"
                },
                "width": 3365,
                "height": 22
              }
            ],
            "height": 22,
            "options": {},
            "width": 3365
          },
          {
            "type": "horizontal-multivec",
            "uid": "S0Js86aARsWbg8_GlwUmew",
            "tilesetUid": "YFDHJn9hSt-K_UYTFe33zQ",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0225_tcga_prevalence_by_cancer_type.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorRange": [
                "rgba(255,255,255,1)",
                "rgba(0,0,0,1)"
              ]
            },
            "width": 3365,
            "height": 100
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "IPJMDwVQRAOCsmWd-nUHhQ",
            "tilesetUid": "Y2PzwH-_QES8VCUdIdBTLA",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0302_tcga_prevalence_by_histology_class.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#FF4500",
                "#32CD32",
                "#008000",
                "#006400",
                "#C2E105",
                "#FFFF00",
                "#66CDAA",
                "#8A91D0",
                "#CD5C5C",
                "#E9967A",
                "#BDB76B",
                "#808080",
                "#C0C0C0",
                "#FFFFFF"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 100
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "KV4dy3iwQPe8qAQBx26BDw",
            "tilesetUid": "SJ_BfKKzTpa8fJ4bLhZKiA",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0302_tcga_prevalence_by_histology_subtype.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#FF4500",
                "#32CD32",
                "#008000",
                "#006400",
                "#C2E105",
                "#FFFF00",
                "#66CDAA",
                "#8A91D0",
                "#CD5C5C",
                "#E9967A",
                "#BDB76B",
                "#808080",
                "#C0C0C0",
                "#FFFFFF"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 163
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "CjeQgz7FTOWH1S8cZe2Fbg",
            "tilesetUid": "XIeQWjmCQXiHkuIJANNhKg",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "log",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "tcga_prevalence_by_archetype_category.mv5",
              "scaleStartPercent": "-0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#FF4500",
                "#32CD32",
                "#008000",
                "#006400",
                "#C2E105",
                "#FFFF00",
                "#66CDAA",
                "#8A91D0",
                "#CD5C5C",
                "#E9967A",
                "#BDB76B",
                "#808080",
                "#C0C0C0",
                "#FFFFFF"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 116
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "P7WTluD-SXSh9ccBOd5JEQ",
            "tilesetUid": "LQzhsO8RRpissAf4jrQZXg",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0301_tcga_prevalence_by_organ_type.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#FF4500",
                "#32CD32",
                "#008000",
                "#006400",
                "#C2E105",
                "#FFFF00",
                "#66CDAA",
                "#8A91D0",
                "#CD5C5C",
                "#E9967A",
                "#BDB76B",
                "#808080",
                "#C0C0C0",
                "#FFFFFF"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 100
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "ME1KDLfuToiWrd21X82qzw",
            "tilesetUid": "YFDHJn9hSt-K_UYTFe33zQ",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0225_tcga_prevalence_by_cancer_type.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#1f77b4",
                "#aec7e8",
                "#ff7f0e",
                "#ffbb78",
                "#2ca02c",
                "#98df8a",
                "#d62728",
                "#ff9896",
                "#9467bd",
                "#c5b0d5",
                "#8c564b",
                "#c49c94",
                "#e377c2",
                "#f7b6d3",
                "#7f7f7f",
                "#c7c7c7",
                "#bcbd22",
                "#dbdb8d",
                "#17becf",
                "#9edae5",
                "#393b79",
                "#5254a3",
                "#6b6ecf",
                "#9c9ede",
                "#637939",
                "#8ca252",
                "#b5cf6b",
                "#cedb9c",
                "#8c6d31",
                "#bd9e39",
                "#e7ba52",
                "#e7cb94",
                "#843c39",
                "#ad494a",
                "#d6616b",
                "#e7969c",
                "#7b4173"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 100
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "EgsjXDgnS8-zBJTi6VaN-Q",
            "tilesetUid": "TxGeZYNESzqeKjI7YrjPSQ",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0301_tcga_prevalence_by_primary_site.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#FF4500",
                "#32CD32",
                "#008000",
                "#006400",
                "#C2E105",
                "#FFFF00",
                "#66CDAA",
                "#8A91D0",
                "#CD5C5C",
                "#E9967A",
                "#BDB76B",
                "#808080",
                "#C0C0C0",
                "#FFFFFF"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 100
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "NVGnql5mSaumZg4Fnta1Pw",
            "tilesetUid": "SjXgY2AWTNGUtMfRL3GcJg",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0302_0226_tcga_prevalence_by_gdc_disease_type.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#FF4500",
                "#32CD32",
                "#008000",
                "#006400",
                "#C2E105",
                "#FFFF00",
                "#66CDAA",
                "#8A91D0",
                "#CD5C5C",
                "#E9967A",
                "#BDB76B",
                "#808080",
                "#C0C0C0",
                "#FFFFFF"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 100
          },
          {
            "type": "horizontal-stacked-bar",
            "uid": "VwdHMFz3S5KGSFF-LMYGvA",
            "tilesetUid": "dIPcMRvWQPOnV7z7Udu3Ow",
            "server": "https://resgen.io/api/v1",
            "options": {
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelShowResolution": true,
              "labelShowAssembly": true,
              "labelColor": "black",
              "labelTextOpacity": 0.4,
              "minHeight": 100,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "heatmapValueScaling": "linear",
              "selectRows": null,
              "selectRowsAggregationMode": "mean",
              "selectRowsAggregationWithRelativeHeight": true,
              "selectRowsAggregationMethod": "client",
              "colorbarBackgroundColor": "#ffffff",
              "colorbarPosition": "topRight",
              "zeroValueColor": null,
              "name": "0302_0226_tcga_prevalence_by_embryonic_layer.mv5",
              "scaleStartPercent": "0.00000",
              "scaleEndPercent": "1.00000",
              "colorScale": [
                "#FF0000",
                "#0000FF",
                "#008000"
              ],
              "backgroundColor": "white",
              "barBorder": true,
              "sortLargestOnTop": true
            },
            "width": 3365,
            "height": 112
          }
        ],
        "left": [],
        "center": [],
        "bottom": [],
        "right": [],
        "whole": [],
        "gallery": []
      },
      "layout": {
        "w": 12,
        "h": 12,
        "x": 0,
        "y": 0
      },
      "uid": "RBzjEy4nTnqTGW7ayM16BQ"
    }
  ],
  "zoomLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  },
  "locationLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  },
  "valueScaleLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  }
}
'''
    )
    return (viewconfig,)


@app.cell
def _(viewconfig):
    import copy

    plugin_url = "https://unpkg.com/higlass-multivec@0.3.3/dist/higlass-multivec.js"
    plugin_types = {"horizontal-multivec", "horizontal-stacked-bar"}

    normalized_viewconfig = copy.deepcopy(viewconfig)

    def inject_plugin_urls(_tracks):
        for _track in _tracks:
            _type = _track.get("type")
            if _type in plugin_types and "plugin_url" not in _track:
                _track["plugin_url"] = plugin_url
            _contents = _track.get("contents")
            if isinstance(_contents, list):
                inject_plugin_urls(_contents)

    for _view in normalized_viewconfig.get("views", []):
        _tracks_by_position = _view.get("tracks", {})
        for _tracks in _tracks_by_position.values():
            if isinstance(_tracks, list):
                inject_plugin_urls(_tracks)

    return (normalized_viewconfig,)


@app.cell
def _(hg, normalized_viewconfig):
    viewconf = hg.Viewconf(**normalized_viewconfig)
    widget = viewconf.widget()

    return viewconf, widget


@app.cell(hide_code=True)
def _(widget):
    widget
    return


if __name__ == "__main__":
    app.run()
